server:
  port: 8080

spring:
  application:
    name: SplitNGo-backend
  docker:
    compose:
      enabled: false

feign:
  client:
    config:
      default:
        connectTimeout: 3000
        readTimeout: 3000
        loggerLevel: full

app:
  cors:
    allowed-origins:
      - http://trip-service:8081