spring:
  devtools:
    restart:
      enabled: true
    livereload:
      enabled: true
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

server:
  port: 8080

trip:
  api:
    url: http://trip-api:8081

app:
  cors:
    allowed-origins:
      - http://localhost:4200
